name: Webseite
services:
  web:
    build: ./app/
    container_name: App
    env_file: ".env"
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ../app
        target: /var/www/html
